manifest:
  remotes:
    - name: Mac-D-Broski
      url-base: https://github.com/Mac-D-Broski
  projects:
    - name: zmk-config
      remote: Mac-D-Broski
      revision: main
      import: app/west.yml
  self:
    path: config
